name: simple_agent
description: multi-skill agent that can perform various tasks using different skills
provider: openai
model: gpt-5.4
skills_directory: ./skills
skills:
  - nasa-image
  - battery-skill

tools_approval_required: true
output_key: agent_response
